# config.py
SECOES = ["1. Gerais", "2. Específicas", "3. Básicas", "4. Profissionais", "5. Avançadas", "6. Reflexão"]
LISTA_PETIANOS = sorted(["", "Ana Carolina", "Ana Clara", "Ana Júlia", "Eric Rullian", "Gildelandio Junior", "Lucas Mossmann (trainee)", "Pedro Paulo"])
LISTA_SEMESTRES = [f"{i}º Semestre" for i in range(1, 11)]
LISTA_CURRICULOS = ["Novo (2023.1)", "Antigo (2005.1)", "Troca de Matriz (Velha -> Nova)"]
NOTA_LABELS = ["N/A", "0", "1", "2", "3", "4", "5"]

ORDEM_QUESTOES = [
    ("q1",  "Projetar e conduzir experimentos e interpretar resultados"),
    ("q2",  "Desenvolver e/ou utilizar novas ferramentas e técnicas"),
    ("q3",  "Conceber, projetar e analisar sistemas, produtos e processos"),
    ("q4",  "Formular, conceber e avaliar soluções para problemas de engenharia"),
    ("q5",  "Analisar e compreender fenômenos físicos e químicos através de modelos"),
    ("q6",  "Comunicação técnica"),
    ("q7",  "Trabalhar e liderar equipes profissionais"),
    ("q8",  "Aplicar ética e legislação no exercício profissional"),
    ("q9",  "Aplicar conhecimentos matemáticos, científicos e tecnológicos"),
    ("q10", "Compreender e modelar transferência de quantidade de movimento, calor e massa"),
    ("q11", "Aplicar conhecimentos de fenômenos de transporte ao projeto"),
    ("q12", "Compreender mecanismos de transformação da matéria e energia"),
    ("q13", "Projetar sistemas de recuperação, separação e purificação"),
    ("q14", "Compreender mecanismos cinéticos de reações químicas"),
    ("q15", "Projetar e otimizar sistemas reacionais e reatores"),
    ("q16", "Projetar sistemas de controle de processos industriais"),
    ("q17", "Projetar e otimizar plantas industriais considerando ambiente e segurança"),
    ("q18", "Aplicação de conhecimentos em projeto básico e dimensionamento"),
    ("q19", "Execução de projetos de produção e melhorias de processos"),
    ("calc_21",   "Cálculo: Analisar grandes volumes de dados"),
    ("calc_52",   "Cálculo: Formação Básica"),
    ("fis_22",    "Física: Analisar criticamente a operação e manutenção de sistemas"),
    ("fis_53",    "Física: Ciência da Engenharia"),
    ("qui_23",    "Química: Aplicar conhecimentos de transformação a processos"),
    ("qui_24",    "Química: Conceber e desenvolver produtos e processos"),
    ("termo_25",  "Termodinâmica: Projetar sistemas de suprimento energético"),
    ("termo_54",  "Termodinâmica: Ciência da Engenharia Química"),
    ("ft_26",     "Fenômenos de Transporte: Aplicar conhecimentos"),
    ("ft_27",     "Fenômenos de Transporte: Comunicação técnica e recursos gráficos"),
    ("mecflu_28", "Mecânica dos Fluidos: Implantar, implementar e controlar soluções"),
    ("mecflu_29", "Mecânica dos Fluidos: Operar e supervisionar instalações"),
    ("op1_30",  "Operações Unitárias I: Inspecionar manutenção"),
    ("op1_55",  "Operações Unitárias I: Tecnologia Industrial"),
    ("op2_31",  "Operações Unitárias II: Elaborar estudos ambientais"),
    ("op2_32",  "Operações Unitárias II: Projetar tratamento ambiental"),
    ("reat_33", "Reatores Químicos: Gerir recursos"),
    ("reat_34", "Reatores Químicos: Controle de qualidade"),
    ("ctrl_35", "Controle de Processos: Supervisão"),
    ("ctrl_36", "Projetos: Gestão de empreendimentos"),
    ("proj_56", "Projetos: Gestão Industrial"),
    ("proj_57", "Projetos: Ética e Humanidades"),
    ("econ_37",  "Engenharia Econômica: Novos conceitos"),
    ("econ_38",  "Engenharia Econômica: Visão global"),
    ("gest_39",  "Gestão da Produção: Comprometimento"),
    ("gest_40",  "Gestão da Produção: Resultados"),
    ("amb_41",   "Engenharia Ambiental: Inovação"),
    ("amb_42",   "Engenharia Ambiental: Novas situações"),
    ("seg_43",   "Segurança: Incertezas"),
    ("seg_44",   "Segurança: Decisão"),
    ("lab_45",   "Laboratório: Criatividade"),
    ("lab_46",   "Laboratório: Relacionamento"),
    ("est_47",   "Estágio: Autocontrole emocional"),
    ("est_48",   "Estágio: Capacidade empreendedora"),
    ("bio_49",   "Biotecnologia: Dados"),
    ("bio_50",   "Biotecnologia: Ferramentas"),
    ("petro_51", "Petróleo: Recuperação"),
    ("petro_52", "Petróleo: Reatores"),
    ("poli_53",  "Polímeros: Cinética"),
    ("poli_54",  "Polímeros: Produtos"),
    ("cat_55",   "Catálise: Mecanismos de transformação"),
    ("cat_56",   "Catálise: Aplicar na produção"),
    ("sim_57",   "Simulação: Dados"),
    ("sim_58",   "Simulação: Comunicação"),
    ("otim_59",  "Otimização: Soluções"),
    ("otim_60",  "Otimização: Modelos"),
    ("tcc_61",   "TCC: Comunicação"),
    ("tcc_62",   "TCC: Liderança"),
    ("q20_indiv","Capacidade de aprender rapidamente novos conceitos (Geral)")
]

ID_PARA_LABEL = {id_: f"Questão {i+1}" for i, (id_, _) in enumerate(ORDEM_QUESTOES)}
ID_PARA_TEXTO = {id_: titulo for (id_, titulo) in ORDEM_QUESTOES}
